version: '3.8'

services:
  impostor:
    build: .
    container_name: impostor-game
    restart: unless-stopped
    expose:
      - "40401:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BASE_PATH=/impostor
    networks:
      - resv-network

networks:
  resv-network:
    external: true




